FROM alpine:3

ARG BUILD_VERSION

LABEL org.opencontainers.image.source=https://github.com/radiusred/ha-sinkhole/dns-resolver
LABEL org.opencontainers.image.description="DNS resolver that uses provided blocklists and then forwards to configured upstream resolvers."
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.version="$BUILD_VERSION"

# Install coredns (which creates the user), gettext (for envsubst),
# and su-exec (to drop privileges)
RUN apk add --no-cache coredns gettext su-exec bash curl jq

COPY Corefile.template /etc/coredns/Corefile.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# fetch the custom built coredns that includes the warnlist plugin (and 
# removes many others) so that we can get rich blocklist metrics
RUN mkdir -p /usr/local/bin
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi && \
    if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi && \
    DOWNLOAD_URL=$(curl -sL https://api.github.com/repos/radiusred/coredns/releases/latest | jq -r '.assets[] | select(.name=="coredns-custom-'"$ARCH"'") | .browser_download_url'); \
    echo $DOWNLOAD_URL; \
    curl -fsSL "$DOWNLOAD_URL" -o /usr/local/bin/coredns && chmod +x /usr/local/bin/coredns 

# Entrypoint will run as root by default
ENTRYPOINT ["/entrypoint.sh"]

# This CMD is passed as arguments ("$@") to the entrypoint.
# This is the default CoreDNS config path.
CMD ["-conf", "/etc/coredns/Corefile"]
