{
 "title": "HA Sinkhole",
 "description": "A dashboard for ha-sinkhole (https://github.com/radiusred/ha-sinkhole)",
 "tags": [
  "dns",
  "coredns"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(coredns_acl_allowed_requests_total[$__range]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (\n  increase(\n    coredns_warnlist_warnlist_hits_total [$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (\n  increase(\n    coredns_warnlist_warnlist_hits_total [$__range]\n  ) \n) /\nsum by(cluster) (\n  increase(\n    coredns_acl_allowed_requests_total [$__range]\n  )\n) *\n100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  coredns_hosts_entries\n  and on(instance, job, cluster)\n  (up == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "timeseries",
   "description": "Sum of DNS requests received for the period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    coredns_warnlist_warnlist_hits_total [2m]\n  )\n)",
     "legendFormat": "Blocked /s "
    },
    {
     "expr": "sum(\n  rate(\n    coredns_acl_allowed_requests_total[2m]\n  )\n)",
     "legendFormat": "Requests /s"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(coredns_dns_request_duration_seconds_bucket{server=\"dns://:1053\", zone=\".\"}[$__range]))\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(coredns_dns_request_duration_seconds_bucket{server=\"dns://:1053\", zone=\".\"}[$__range]))\n)",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le) (rate(coredns_dns_request_duration_seconds_bucket{server=\"dns://:1053\", zone=\".\"}[$__range]))\n)",
     "legendFormat": "90th"
    }
   ]
  },
  {
   "title": "Request Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(coredns_dns_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(coredns_cache_hits_total[$__range]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(to) (\n    round(\n      increase(coredns_proxy_conn_cache_misses_total[$__range])\n      +\n      increase(coredns_proxy_conn_cache_hits_total[$__range])\n    )\n  ),\n  \"to\", \"$1\", \"to\", \"([^:]+):.*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rcode) (increase(coredns_dns_responses_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "stat",
   "description": "Number of server panics recorded",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(coredns_panics_total[$__range]))",
     "legendFormat": "panics"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Failed healthchecks of the dns-node services",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(coredns_health_request_failures_total[$__range]))",
     "legendFormat": "failed health"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Failed healthchecks of the upstream forwarders",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(coredns_proxy_healthcheck_failures_total[$__range]))",
     "legendFormat": "failed upstream"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rejections due to maximum number of concurrent upstream connections reached",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(coredns_forward_max_concurrent_rejects_total[$__range]))",
     "legendFormat": "upstream reject"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Failure to reload configuration due to errors",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(coredns_reload_failed_total[$__range]))",
     "legendFormat": "config failed"
    }
   ]
  },
  { "title": "Process metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total[2m])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Resident memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DNS Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_network_receive_bytes_total[2m]))",
     "legendFormat": "{{ instance }} rx"
    },
    {
     "expr": "sum by (instance) (rate(process_network_transmit_bytes_total[5m]))",
     "legendFormat": "{{instance}} tx"
    }
   ]
  }
 ]
}