FROM alpine:3

ARG BUILD_VERSION

LABEL org.opencontainers.image.source=https://github.com/radiusred/ha-sinkhole/blocklist_updater
LABEL org.opencontainers.image.description="A simple container to download and update blocklists for ha-sinkhole."
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.version="$BUILD_VERSION"

RUN apk add --no-cache python3

COPY process_lists.py /usr/local/bin/process_lists.py
RUN chmod +x /usr/local/bin/process_lists.py

ENTRYPOINT ["/usr/local/bin/process_lists.py"]
CMD ["/data/blocklists.hosts"]
